// === NEW ENTRIES FROM UN TREATY COLLECTION SCRAPE ===
// 68 new treaties (IDs 41-108)

  {
    id: 41,
    name: 'Vienna Convention on Diplomatic Relations',
    mtdsg_no: 'III-3',
    signed: null, ratified: 1975,
    era: 'Mao (1949–76)',
    cat: 'Political & territorial',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1961,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['19 The Government of the People\'s Republic of China holds reservations on the provisions about nuncios and the representa- tive of the Holy See in articles 14 and 16 and on the provisions of paragraphs 2, 3 and 4 of article 37.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=III-3&chapter=3&clang=_en',
    tags: [],
    notes: '19 The Government of the People\'s Republic of China holds reservations on the provisions about nuncios and the representa- tive of the Holy See in articles 14 and 16 and on the provisions of paragr...',
  },
  {
    id: 42,
    name: 'Vienna Convention on Consular Relations',
    mtdsg_no: 'III-6',
    signed: null, ratified: 1979,
    era: 'Deng (1978–92)',
    cat: 'Political & territorial',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1963,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=III-6&chapter=3&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection III-6.',
  },
  {
    id: 43,
    name: 'United Nations Convention on Jurisdictional Immunities of States and Their Property',
    mtdsg_no: 'III-13',
    signed: 2005, ratified: null,
    era: 'Hu (2002–12)',
    cat: 'Political & territorial',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 2004,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=III-13&chapter=3&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection III-13.',
  },
  {
    id: 44,
    name: 'International Convention on the Elimination of All Forms of Racial Discrimination',
    mtdsg_no: 'IV-2',
    signed: null, ratified: 1981,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1966,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['5 , 6 , 7 , 8'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-2&chapter=4&clang=_en',
    tags: [],
    notes: '5 , 6 , 7 , 8 | 22 Reservation: The People\'s Republic of China has reservations on the provisions of article 22 of the Convention and will not be bound by it. (The reservation was circulated by the Secretary-Gener...',
  },
  {
    id: 45,
    name: 'International Convention on the Suppression and Punishment of the Crime of Apartheid',
    mtdsg_no: 'IV-7',
    signed: null, ratified: 1983,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1973,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-7&chapter=4&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection IV-7.',
  },
  {
    id: 46,
    name: 'International Convention against Apartheid in Sports',
    mtdsg_no: 'IV-10',
    signed: 1987, ratified: null,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1985,
    entry_into_force: null,
    signing_lag_years: 2,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-10&chapter=4&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection IV-10.',
  },
  {
    id: 47,
    name: 'Optional Protocol to the Convention on the Rights of the Child on the involvement of children in armed conflict',
    mtdsg_no: 'IV-11-b',
    signed: 2001, ratified: 2008,
    era: 'Hu (2002–12)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2000,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: 7,
    adoption_percentile: null,
    reservations: ['Declaration: 1. The minimum age for citizens voluntarily entering the Armed Forces of the People’s Republic of China is 17 years of age. 2. The Government of the People’s Republic of China is applying the following safeguard measures in implementing the foregoing provision: (1) The Military Service Law of the People’s Republic of China provides that each year, male citizens who have reached 18 years of age by 31 December shall be recruited for active service. To meet the needs of the armed forces and on the principle of voluntary participation, male and female citizens who have not yet reached 18 years of age by 31 December of a given year may be recruited for active service. Citizens eligible for enlistment who have registered for military service but who have not been recruited for active service shall serve in the enlistees reserves, for which the minimum age is 18. The Regulations on the Recruitment of Soldiers formulated by the State Council and the Central Military Commission of the People’s Republic of China on the basis of the Military Service Law of the People’s Republic of China, provides that in order to meet the needs of the armed forces and on the principle of voluntary participation, male and female citizens who have not yet reached 17 years of age by 31 December of a given year may be recruited for active service. (2) The Criminal Law of the People’s Republic of China provides that whoever engages in favouritism and commits irregularities in conscription work or accepts or delivers unqualified recruits shall be sentenced to not more than three years of fixed-term imprisonment or criminal detention, if the circumstances are serious; such an offender is to be sentenced to not less than three years but not more than seven years of fixed-term imprisonment if the consequences are especially serious. (3) Under the provisions of the Regulations on Honest and Non-Corrupt Recruitment, formulated by the State Council and the Central Military Commission of the People’s Republic of China, neither the loosening of recruitment conditions nor the lowering of enlistment standards are to be allowed. They further provide for the implementation of a system of visiting the homes and work units of youth who enlist, and for verifying the ages of enlisting youth.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-11-b&chapter=4&clang=_en',
    tags: [],
    notes: 'Declaration: 1. The minimum age for citizens voluntarily entering the Armed Forces of the People’s Republic of China is 17 years of age. 2. The Government of the People’s Republic of China is apply...',
  },
  {
    id: 48,
    name: 'Optional Protocol to the Convention on the Rights of the Child on the sale of children, child prostitution and child pornography',
    mtdsg_no: 'IV-11-c',
    signed: 2000, ratified: 2002,
    era: 'Jiang (1992–02)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2000,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 2,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IV-11-c&chapter=4&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection IV-11-c.',
  },
  {
    id: 49,
    name: 'Convention relating to the Status of Refugees',
    mtdsg_no: 'V-2',
    signed: null, ratified: 1982,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1951,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['“[Subject to] reservations on the following articles: (1).	The latter half of article 14, which reads ‘In the territory of any other Contracting State, he shall be accorded the same protection as is accorded in that territory to nationals of the country in which he has his habitual residence.’ (2).		Article 16 (3).”'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=V-2&chapter=5&clang=_en',
    tags: [],
    notes: '“[Subject to] reservations on the following articles: (1). The latter half of article 14, which reads ‘In the territory of any other Contracting State, he shall be accorded the same protection as i...',
  },
  {
    id: 50,
    name: 'Convention relating to the Status of Stateless Persons',
    mtdsg_no: 'V-3',
    signed: null, ratified: null,
    era: null,
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'in force',
    treaty_opened: 1954,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=V-3&chapter=5&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection V-3.',
  },
  {
    id: 51,
    name: 'Protocol amending the Agreements, Conventions and Protocols on Narcotic Drugs, concluded at The Hague on 23 January 1912, at Geneva on 11 February 1925 and 19 February 1925, and 13 July 1931, at Bangkok on 27 November 1931 and at Geneva on 26 June 1936. Lake Success, New York, 11 December 1946',
    mtdsg_no: 'VI-1',
    signed: null, ratified: 1946,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-1&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-1.',
  },
  {
    id: 52,
    name: 'Convention for Limiting the Manufacture and Regulating the Distribution of Narcotic Drugs',
    mtdsg_no: 'VI-7',
    signed: 1946, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1931,
    entry_into_force: null,
    signing_lag_years: 15,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-7&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-7.',
  },
  {
    id: 53,
    name: 'Convention for the Suppression of the Illicit Traffic in Dangerous Drugs',
    mtdsg_no: 'VI-11',
    signed: 1946, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1936,
    entry_into_force: null,
    signing_lag_years: 10,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-11&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-11.',
  },
  {
    id: 54,
    name: 'Protocol Bringing under International Control Drugs Outside the Scope of the Convention of 13 July 1931 for Limiting the Manufacture and Regulating the Distribution of Narcotic Drugs, as amended by the Protocol signed at Lake Success, New York, on 11 December 1946',
    mtdsg_no: 'VI-13',
    signed: null, ratified: 1948,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1948,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-13&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-13.',
  },
  {
    id: 55,
    name: 'Protocol for Limiting and Regulating the Cultivation of the Poppy Plant, the Production of, International and Wholesale Trade in, and use of Opium',
    mtdsg_no: 'VI-14',
    signed: null, ratified: 1954,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1953,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-14&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-14.',
  },
  {
    id: 56,
    name: 'Convention on psychotropic substances',
    mtdsg_no: 'VI-16',
    signed: null, ratified: 1985,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1971,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: "1.	The Chinese Government has reservation on paragraph 2, article 48 of the Single Convention on Narcotic Drugs of 1961 [as amended] and on paragraph 2, article 31 of the Convention on Psychotropic Substances of 1971. Declaration: 2.	The signature and ratification by the Taiwan authorities in the name of China respectively on 30 March 1961 and 12 May 1969 of the Single Convention on Narcotic Drugs of 1961 and their signature of the Convention on Psychotropic Substances of 1971 on 21 February 1971 are all illegal and therefore null and void."'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-16&chapter=6&clang=_en',
    tags: [],
    notes: 'Reservation: "1. The Chinese Government has reservation on paragraph 2, article 48 of the Single Convention on Narcotic Drugs of 1961 [as amended] and on paragraph 2, article 31 of the Convention o...',
  },
  {
    id: 57,
    name: 'Single Convention on Narcotic Drugs, 1961, as amended by the Protocol amending the Single Convention on Narcotic Drugs, 1961',
    mtdsg_no: 'VI-18',
    signed: null, ratified: 1985,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1975,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-18&chapter=6&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VI-18.',
  },
  {
    id: 58,
    name: 'United Nations Convention against Illicit Traffic in Narcotic Drugs and Psychotropic Substances',
    mtdsg_no: 'VI-19',
    signed: 1988, ratified: 1989,
    era: 'Deng (1978–92)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1988,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 1,
    adoption_percentile: null,
    reservations: ['Declaration made upon signature and confirmed upon ratification: Under the Article 32, paragraph 4, China does not consider itself bound by paragraphs 2 and 3 of that article.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VI-19&chapter=6&clang=_en',
    tags: [],
    notes: 'Declaration made upon signature and confirmed upon ratification: Under the Article 32, paragraph 4, China does not consider itself bound by paragraphs 2 and 3 of that article. | 30 November 2012 1. The Ministry of Foreign Affairs of the People’s Republic of China is designated as the communication authority for cooperation on extradition for the purpose of Article 6 of the...',
  },
  {
    id: 59,
    name: 'Protocol signed at Lake Success, New York, on 12 November 1947, to amend the Convention for the Suppression of the Traffic in Women and Children, concluded at Geneva on 30 September 1921, and the Convention for the Suppression of the Traffic in Women of Full Age, concluded at Geneva on 11 October 1933. Lake Success, New York, 12 November 1947',
    mtdsg_no: 'VII-1',
    signed: null, ratified: 1947,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VII-1&chapter=7&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VII-1.',
  },
  {
    id: 60,
    name: 'International Convention for the Suppression of the Traffic in Women and Children, concluded at Geneva on 30 September 1921, as amended by the Protocol signed at Lake Success, New York, on 12 November 1947. Lake Success, 12 November 1947',
    mtdsg_no: 'VII-2',
    signed: 1947, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VII-2&chapter=7&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VII-2.',
  },
  {
    id: 61,
    name: 'Protocol amending the International Agreement for the Suppression of the White Slave Traffic, signed at Paris on 18 May 1904, and the International Convention for the Suppression of the White Slave Traffic, signed at Paris on 4 May 1910. Lake Success, New York, 4 May 1949',
    mtdsg_no: 'VII-6',
    signed: null, ratified: 1949,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VII-6&chapter=7&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VII-6.',
  },
  {
    id: 62,
    name: 'International Agreement for the Suppression of the White Slave Traffic, signed at Paris on 18 May 1904, amended by the Protocol signed at Lake Success, New York, 4 May 1949. Lake Success, New York, 4 May 1949',
    mtdsg_no: 'VII-7',
    signed: 1949, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VII-7&chapter=7&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VII-7.',
  },
  {
    id: 63,
    name: 'Protocol to amend the Convention for the suppression of the circulation of, and traffic in, obscene publications, concluded at Geneva on 12 September 1923. Lake Success, New York, 12 November 1947',
    mtdsg_no: 'VIII-1',
    signed: null, ratified: 1947,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VIII-1&chapter=8&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VIII-1.',
  },
  {
    id: 64,
    name: 'Convention for the Suppression of the Circulation of, and Traffic in, Obscene Publications, concluded at Geneva on 12 September 1923 and amended by the Protocol signed at Lake Success, New York, on 12 November 1947',
    mtdsg_no: 'VIII-2',
    signed: 1947, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1947,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VIII-2&chapter=8&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VIII-2.',
  },
  {
    id: 65,
    name: 'Protocol amending the Agreement for the Suppression of the Circulation of Obscene Publications, signed at Paris, on 4 May 1910. Lake Success, New York, 4 May 1949',
    mtdsg_no: 'VIII-4',
    signed: null, ratified: 1949,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VIII-4&chapter=8&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VIII-4.',
  },
  {
    id: 66,
    name: 'Agreement for the Suppression of the Circulation of Obscene Publications, signed at Paris on 4 May 1910, amended by the Protocol signed at Lake Success, New York, 4 May 1949',
    mtdsg_no: 'VIII-5',
    signed: 1949, ratified: null,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1949,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=VIII-5&chapter=8&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection VIII-5.',
  },
  {
    id: 67,
    name: 'Agreement on the establishment of the International Vaccine Institute',
    mtdsg_no: 'IX-3',
    signed: 1997, ratified: 1997,
    era: 'Jiang (1992–02)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1996,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: 0,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IX-3&chapter=9&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection IX-3.',
  },
  {
    id: 68,
    name: 'WHO Framework Convention on Tobacco Control',
    mtdsg_no: 'IX-4',
    signed: 2003, ratified: 2005,
    era: 'Hu (2002–12)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2003,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 2,
    adoption_percentile: null,
    reservations: ['Declaration: In accordance with the provision of Article 16, paragraph 5.....the People\'s Republic of China indicates hereby its commitment to prohibit the introduction of tobacco vending machines within its jurisdiction.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IX-4&chapter=9&clang=_en',
    tags: [],
    notes: 'Declaration: In accordance with the provision of Article 16, paragraph 5.....the People\'s Republic of China indicates hereby its commitment to prohibit the introduction of tobacco vending machines ...',
  },
  {
    id: 69,
    name: 'Protocol to Eliminate Illicit Trade in Tobacco Products. Seoul, 12 November 2012',
    mtdsg_no: 'IX-4-a',
    signed: 2013, ratified: null,
    era: 'Xi (2012–)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=IX-4-a&chapter=9&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection IX-4-a.',
  },
  {
    id: 70,
    name: 'Agreement establishing the International Fund for Agricultural Development',
    mtdsg_no: 'X-8',
    signed: null, ratified: 1980,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1976,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-8&chapter=10&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection X-8.',
  },
  {
    id: 71,
    name: 'United Nations Convention on Contracts for the International Sale of Goods',
    mtdsg_no: 'X-10',
    signed: 1981, ratified: 1986,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1980,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: 5,
    adoption_percentile: null,
    reservations: ['12 4 May 2022 Declaration: In accordance with the Basic Law of the Hong Kong Special Administrative Region of the People`s Republic of China (“the PRC”), the Government of the PRC decides that the Convention shall apply to the Hong Kong Special Administrative Region (hereinafter referred to as “the HKSAR”) of the PRC and declares that the declaration that the PRC is not bound by subparagraph (b) of paragraph (1) of article 1 of the Convention shall not apply to the HKSAR of the PRC.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-10&chapter=10&clang=_en',
    tags: [],
    notes: '12 4 May 2022 Declaration: In accordance with the Basic Law of the Hong Kong Special Administrative Region of the People`s Republic of China (“the PRC”), the Government of the PRC decides that the ...',
  },
  {
    id: 72,
    name: 'Charter of the Asian and Pacific Development Centre. Bangkok, 1 April 1982',
    mtdsg_no: 'X-11',
    signed: null, ratified: 1983,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-11&chapter=10&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection X-11.',
  },
  {
    id: 73,
    name: 'Agreement to establish the South Centre',
    mtdsg_no: 'X-14',
    signed: null, ratified: 1995,
    era: 'Jiang (1992–02)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1994,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-14&chapter=10&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection X-14.',
  },
  {
    id: 74,
    name: 'United Nations Convention on the Use of Electronic Communications in International Contracts',
    mtdsg_no: 'X-18',
    signed: 2006, ratified: null,
    era: 'Hu (2002–12)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 2005,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-18&chapter=10&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection X-18.',
  },
  {
    id: 75,
    name: 'Framework Agreement on Facilitation of Cross-border Paperless Trade in Asia and the Pacific. Bangkok, 19 May 2016',
    mtdsg_no: 'X-20',
    signed: 2017, ratified: 2020,
    era: 'Xi (2012–)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: 3,
    adoption_percentile: null,
    reservations: ['Declaration: In accordance with the Basic Law of the Hong Kong Special Administrative Region of the People’s Republic of China and the Basic Law of the Macao Special Administrative Region of the People’s Republic of China, the Government of the People’s Republic of China decides that the Agreement applies to the Hong Kong Special Administrative Region and the Macao Special Administrative Region of the People’s Republic of China.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-20&chapter=10&clang=_en',
    tags: [],
    notes: 'Declaration: In accordance with the Basic Law of the Hong Kong Special Administrative Region of the People’s Republic of China and the Basic Law of the Macao Special Administrative Region of the Pe...',
  },
  {
    id: 76,
    name: 'United Nations Convention on the International Effects of Judicial Sales of Ships',
    mtdsg_no: 'X-21',
    signed: 2023, ratified: null,
    era: 'Xi (2012–)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 2022,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=X-21&chapter=10&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection X-21.',
  },
  {
    id: 77,
    name: 'Customs Convention on Containers, 1972',
    mtdsg_no: 'XI-A-15',
    signed: null, ratified: 1986,
    era: 'Deng (1978–92)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1972,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XI-A-15&chapter=11&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XI-A-15.',
  },
  {
    id: 78,
    name: 'Customs Convention on the International Transport of Goods under Cover of TIR Carnets (TIR Convention)',
    mtdsg_no: 'XI-A-16',
    signed: null, ratified: 2016,
    era: 'Xi (2012–)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1975,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: The People’s Republic of China does not accept the constraints imposed in article 57, paragraphs 2 through 6, of the 1975 Convention on the International Transport of Goods.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XI-A-16&chapter=11&clang=_en',
    tags: [],
    notes: 'Reservation: The People’s Republic of China does not accept the constraints imposed in article 57, paragraphs 2 through 6, of the 1975 Convention on the International Transport of Goods.',
  },
  {
    id: 79,
    name: 'Convention on the International Maritime Organization',
    mtdsg_no: 'XII-1',
    signed: null, ratified: 1973,
    era: 'Mao (1949–76)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1948,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['I am instructed by the Minister of Foreign Affairs of the People\'s Republic of China, with reference to the communication which the United Kingdom Mission to the United Nations addressed to Your Excellency today, to notify Your Excellency of the declaration of the People\'s Republic of China as follows: In accordance with the Joint Declaration of the Government of the People\'s Republic of China and the Government of the United Kingdom of Great Britaid Norn Ireland on the Question of Hong Kong signed in Beijing on 19 December 1984, the People\'s Republic of China will resume the exercise of sovereignty over Hong Kong with effect from 1 July 1997.  Hong Kong, as an inseparable part of the territory of the People\'s Republic of China, will become a special administrative region with effect from that date.  The People\'s Republic of China will have international responsibility for the Hong Kong Special Administrative Region. I am also instructed to declare that since China is a contracting State to the Convention on the Maritime Organization, signed in Geneva on 6 March 1948, and the Government of the People\'s Republic of China accepted the Convention on 1 March 1973, the said Convention will apply to the Hong Kong Special Administrative Region with effect from 1 July 1997.  Accordingly, the Government of the People\'s Republic of China notifies you that, with effect from 1 July 1997, the Hong Kong Special Administrative Region will continue to meet the essential requirements of the Convention for being an associate member of the Organization, and therefore may, using the name of "Hong Kong, China", continue to be an associate member of the Organisation. I avail myself of this opportunity to renew to Your Excellency the assurances of my highest consideration. (Signed)  Li Luye'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XII-1&chapter=12&clang=_en',
    tags: [],
    notes: 'I am instructed by the Minister of Foreign Affairs of the People\'s Republic of China, with reference to the communication which the United Kingdom Mission to the United Nations addressed to Your Ex...',
  },
  {
    id: 80,
    name: 'Convention on a Code of Conduct for Liner Conferences',
    mtdsg_no: 'XII-6',
    signed: null, ratified: 1980,
    era: 'Deng (1978–92)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1974,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['The joint shipping services established between the People\'s Republic of China and any other country through consultations and on a basis that the parties concerned may deem appropriate, are totally different from liner conferences in nature, and the provisions of the United Nations Convention on a Code of Conduct for Liner Conferences shall not be applicable thereto.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XII-6&chapter=12&clang=_en',
    tags: [],
    notes: 'The joint shipping services established between the People\'s Republic of China and any other country through consultations and on a basis that the parties concerned may deem appropriate, are totall...',
  },
  {
    id: 81,
    name: 'Convention for the Protection of Producers of Phonograms against Unauthorized Duplication of their Phonograms',
    mtdsg_no: 'XIV-4',
    signed: null, ratified: 1993,
    era: 'Jiang (1992–02)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1971,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XIV-4&chapter=14&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XIV-4.',
  },
  {
    id: 82,
    name: 'Convention on the Nationality of Married Women',
    mtdsg_no: 'XVI-2',
    signed: 1957, ratified: 1958,
    era: 'Mao (1949–76)',
    cat: 'Human rights',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1957,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 1,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVI-2&chapter=16&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XVI-2.',
  },
  {
    id: 83,
    name: 'International Convention Against the Taking of Hostages',
    mtdsg_no: 'XVIII-5',
    signed: null, ratified: 1993,
    era: 'Jiang (1992–02)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1979,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: The People\'s Republic of China makes its reservation to article 16, paragraph 1, and does not consider itself bound by the provisions of article 16, paragraph 1, of the Convention.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-5&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation: The People\'s Republic of China makes its reservation to article 16, paragraph 1, and does not consider itself bound by the provisions of article 16, paragraph 1, of the Convention.',
  },
  {
    id: 84,
    name: 'Convention on the Prevention and Punishment of Crimes against Internationally Protected Persons, including Diplomatic Agents',
    mtdsg_no: 'XVIII-7',
    signed: null, ratified: 1987,
    era: 'Deng (1978–92)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1973,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['[The People\'s Republic of China] declares that, in accordance with paragraph 2 of article 13 of the Convention, the People\'s Republic of China has reservations on paragraph l of article 13 of the Convention and does not consider itself bound by the provisions of the said paragraph.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-7&chapter=18&clang=_en',
    tags: [],
    notes: '[The People\'s Republic of China] declares that, in accordance with paragraph 2 of article 13 of the Convention, the People\'s Republic of China has reservations on paragraph l of article 13 of the C...',
  },
  {
    id: 85,
    name: 'Convention on the Safety of United Nations and Associated Personnel',
    mtdsg_no: 'XVIII-8',
    signed: null, ratified: 2004,
    era: 'Hu (2002–12)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1994,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: The People\'s Republic of China makes a reservation with regard to Article 22, paragraph 1 of the Convention on the Safety of United Nations and Associated Personnel and is not bound by the provisions of Article 22, paragraph 1.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-8&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation: The People\'s Republic of China makes a reservation with regard to Article 22, paragraph 1 of the Convention on the Safety of United Nations and Associated Personnel and is not bound by... | 27 July 2007 Pursuant to article 10, paragraph 2 of the Convention, the Hong Kong Special Administrative Region of the People\'s Republic of China has established its jurisdiction referred to in art...',
  },
  {
    id: 86,
    name: 'International Convention for the Suppression of Terrorist Bombings',
    mtdsg_no: 'XVIII-9',
    signed: null, ratified: 2001,
    era: 'Jiang (1992–02)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1997,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: "... China accedes to the International Convention for the Suppression of Terrorist Bombing, done at New York on 15 December 1997, and declares that it does not consider itself bound by paragraph 1 of Article 20 of the Convention."'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-9&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation: "... China accedes to the International Convention for the Suppression of Terrorist Bombing, done at New York on 15 December 1997, and declares that it does not consider itself bound b...',
  },
  {
    id: 87,
    name: 'International Convention for the Suppression of the Financing of Terrorism',
    mtdsg_no: 'XVIII-11',
    signed: 2001, ratified: 2006,
    era: 'Hu (2002–12)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1999,
    entry_into_force: null,
    signing_lag_years: 2,
    ratification_lag_years: 5,
    adoption_percentile: null,
    reservations: ['Reservation and declaration: 1.     The People\'s Republic of China shall not be bound by paragraph 1 of article 24 of the Convention. [...] 3. As to the Macao Special Administrative Region of the People\'s Republic of China, the following three Conventions shall not be included in the annex referred to in Article 2, paragraph 1, subparagraph (a) of the Convention: (1)		Convention on the Physical Protection of Nuclear Material, adopted at Vienna on 3 March 1980. (2)		Convention for the Suppression of Unlawful Acts against the Safety of Maritime Navigation, done at Rome on 10 March 1988. (3) Protocol for the Suppression of Unlawful Acts against the Safety of Fixed Platforms located on the Continental Shelf, done at Rome on 10 March 1988.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-11&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation and declaration: 1. The People\'s Republic of China shall not be bound by paragraph 1 of article 24 of the Convention. [...] 3. As to the Macao Special Administrative Region of the Peopl... | In accordance with paragraph 3 of Article 7 of the Convention, the People\'s Republic of China has established the jurisdiction over five offences stipulated in paragraph 2 of Article 7 of the Conve...',
  },
  {
    id: 88,
    name: 'Protocol to Prevent, Suppress and Punish Trafficking in Persons, Especially Women and Children, supplementing the United Nations Convention against Transnational Organized Crime',
    mtdsg_no: 'XVIII-12-a',
    signed: null, ratified: 2010,
    era: 'Hu (2002–12)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2000,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: The People’s Republic of China shall not be bound by paragraph 2 of Article 15 of the Protocol. Declaration: Unless otherwise notified by the Government, the Protocol shall not apply to the Hong Kong Special Administrative Region of the People’s Republic of China.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-12-a&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation: The People’s Republic of China shall not be bound by paragraph 2 of Article 15 of the Protocol. Declaration: Unless otherwise notified by the Government, the Protocol shall not apply t...',
  },
  {
    id: 89,
    name: 'Protocol against the Illicit Manufacturing of and Trafficking in Firearms, Their Parts and Components and Ammunition, supplementing the United Nations Convention against Transnational Organized Crime',
    mtdsg_no: 'XVIII-12-c',
    signed: 2002, ratified: 2023,
    era: 'Xi (2012–)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2001,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: 21,
    adoption_percentile: null,
    reservations: ['Reservation: The People’s Republic of China is not bound by article 16, paragraph 2, of the Firearms Protocol. Declarations: 1.  In respect of article 2 of the Firearms Protocol, the People’s Republic of China has already enacted stricter domestic legal provisions to prevent, combat and eradicate the illicit manufacturing of and trafficking in firearms, their parts and components and ammunition. 2.  Under the Basic Law of the Hong Kong Special Administrative Region of the People’s Republic of China and the Basic Law of the Macao Special Administrative Region of the People\'s Republic of China, the Government of the People’s Republic of China decides that the Firearms Protocol applies to the Hong Kong Special Administrative Region and to the Macao Special Administrative Region of the People’s Republic of China. 3.  The reservations made by the People’s Republic of China to article 16, paragraph 2, of the Firearms Protocol and the declarations made regarding article 2 of the Firearms Protocol shall also be applied to the Hong Kong Special Administrative Region and to the Macao Special Administrative Region.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-12-c&chapter=18&clang=_en',
    tags: [],
    notes: 'Reservation: The People’s Republic of China is not bound by article 16, paragraph 2, of the Firearms Protocol. Declarations: 1. In respect of article 2 of the Firearms Protocol, the People’s Republ...',
  },
  {
    id: 90,
    name: 'International Convention for the Suppression of Acts of Nuclear Terrorism',
    mtdsg_no: 'XVIII-15',
    signed: 2005, ratified: 2010,
    era: 'Hu (2002–12)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2005,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 5,
    adoption_percentile: null,
    reservations: ['Declaration: The People\'s Republic of China does not consider itself bound by paragraph 1 of article 23 of the Convention.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-15&chapter=18&clang=_en',
    tags: [],
    notes: 'Declaration: The People\'s Republic of China does not consider itself bound by paragraph 1 of article 23 of the Convention. | In accordance with paragraph 3 of article 9 of the Convention, the People\'s Republic of China has established the jurisdiction specified in paragraph 2 of article 9 of the Convention.',
  },
  {
    id: 91,
    name: 'United Nations Convention against Cybercrime; Strengthening International Cooperation for Combating Certain Crimes Committed by Means of Information and Communications Technology Systems and for the Sharing of Evidence in Electro...',
    mtdsg_no: 'XVIII-16',
    signed: 2025, ratified: null,
    era: 'Xi (2012–)',
    cat: 'Military & security',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 2024,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XVIII-16&chapter=18&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XVIII-16.',
  },
  {
    id: 92,
    name: 'Agreement Establishing The Common Fund For Commodities',
    mtdsg_no: 'XIX-21',
    signed: 1980, ratified: 1981,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1980,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 1,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XIX-21&chapter=19&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XIX-21.',
  },
  {
    id: 93,
    name: 'Terms of Reference of the International Copper Study Group',
    mtdsg_no: 'XIX-35',
    signed: null, ratified: 1990,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1989,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XIX-35&chapter=19&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XIX-35.',
  },
  {
    id: 94,
    name: 'Agreement for the Implementation of the Provisions of the United Nations Convention on the Law of the Sea of 10 December 1982 relating to the Conservation and Management of Straddling Fish Stocks and Highly Migratory Fish Stocks',
    mtdsg_no: 'XXI-7',
    signed: 1996, ratified: null,
    era: 'Jiang (1992–02)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 1995,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXI-7&chapter=21&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXI-7.',
  },
  {
    id: 95,
    name: 'Agreement under the United Nations Convention on the Law of the Sea on the Conservation and Sustainable Use of Marine Biological Diversity of Areas beyond National Jurisdiction',
    mtdsg_no: 'XXI-10',
    signed: 2023, ratified: 2025,
    era: 'Xi (2012–)',
    cat: 'Maritime & territory',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2023,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 2,
    adoption_percentile: null,
    reservations: ['15 December 2025 Declarations made at the time of ratification I. 	Pursuant to Article 10 Paragraph 1 and Article 70 of the Agreement, the People’s Republic of China makes an exception to the application of the provisions of the Agreement. For the People’s Republic of China, the provisions of the Agreement apply only to activities with respect to marine genetic resources and digital sequence information on marine genetic resources of areas beyond national jurisdiction collected and generated after the entry into force of the Agreement for the People’s Republic of China, and do not apply to the utilization of marine genetic resources and digital sequence information on marine genetic resources of areas beyond national jurisdiction collected or generated before the entry into force of the Agreement for the People’s Republic of China. II.	 Pursuant to Article 71 of the Agreement, the People’s Republic of China makes the following declarations: i.	In accordance with Article 1 Paragraph 2, Article 3, Article 6, Article 18 and other related provisions of the Agreement, the Agreement shall apply only to the high seas and the Area; the Agreement and its implementation shall be without prejudice to the sovereignty, sovereign rights or jurisdiction of a State, including in respect of any disputes relating thereto; the establishment of area-based management tools under the Agreement, including marine protected areas, shall not include any areas within national jurisdiction or any areas involving any claims of a State to sovereignty, sovereign rights or jurisdiction. Based on the foregoing, the territorial sovereignty of the People’s Republic of China shall under no circumstances be affected by the Agreement or its implementation; the maritime rights of the People’s Republic of China in areas within its national jurisdiction shall under no circumstances be affected by the Agreement or its implementation. ii.	In accordance with Article 2, Article 5 and other related provisions of the Agreement, the Agreement and its implementation shall properly address the relationship between conservation and sustainable use of marine biological diversity, and shall cooperate and coordinate with relevant international legal instruments, frameworks and bodies without undermining their competence or operation. iii.	In accordance with Article 47 Paragraph 5 of the Agreement, the Conference of the Parties to the Agreement shall make every effort to adopt decisions and recommendations by consensus. III.	 Unless otherwise notified by the Government of the People’s Republic of China, the Agreement shall not apply to the Hong Kong Special Administrative Region of the People’s Republic of China or to the Macao Special Administrative Region of the People’s Republic of China.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXI-10&chapter=21&clang=_en',
    tags: [],
    notes: '15 December 2025 Declarations made at the time of ratification I. Pursuant to Article 10 Paragraph 1 and Article 70 of the Agreement, the People’s Republic of China makes an exception to the applic...',
  },
  {
    id: 96,
    name: 'Convention on the Recognition and Enforcement of Foreign Arbitral Awards',
    mtdsg_no: 'XXII-1',
    signed: null, ratified: 1987,
    era: 'Deng (1978–92)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1958,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['1.	The People\'s Republic of China will apply the Conven- tion, only on the basis of reciprocity, to the recognition and en- forcement of arbitral awards made in the territory of another Contracting State; 2.	The People\'s Republic of China will apply the Conven- tion only to differences arising out of legal relationships, whether contractual or not, which are considered as commercial under the national law of the People\'s Republic of China.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXII-1&chapter=22&clang=_en',
    tags: [],
    notes: '1. The People\'s Republic of China will apply the Conven- tion, only on the basis of reciprocity, to the recognition and en- forcement of arbitral awards made in the territory of another Contracting...',
  },
  {
    id: 97,
    name: 'United Nations Convention on International Settlement Agreements Resulting from Mediation',
    mtdsg_no: 'XXII-4',
    signed: 2019, ratified: null,
    era: 'Xi (2012–)',
    cat: 'Economic & trade',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: false, imp: false,
    status: 'signed only',
    treaty_opened: 2018,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'mixed',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXII-4&chapter=22&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXII-4.',
  },
  {
    id: 98,
    name: 'Vienna Convention on the Law of Treaties',
    mtdsg_no: 'XXIII-1',
    signed: null, ratified: 1997,
    era: 'Jiang (1992–02)',
    cat: 'Political & territorial',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1969,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Reservation: 1.		The People\'s Republic of China makes its reservation to article 66 of the said Convention. Declaration: 2.		The signature to the said Convention by the Taiwan authorities on 27 April 1970 in the name of "China" is illegal and therefore null and void.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXIII-1&chapter=23&clang=_en',
    tags: [],
    notes: 'Reservation: 1. The People\'s Republic of China makes its reservation to article 66 of the said Convention. Declaration: 2. The signature to the said Convention by the Taiwan authorities on 27 April...',
  },
  {
    id: 99,
    name: 'Convention on registration of objects launched into outer space',
    mtdsg_no: 'XXIV-1',
    signed: null, ratified: 1988,
    era: 'Deng (1978–92)',
    cat: 'Technology & science',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1974,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXIV-1&chapter=24&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXIV-1.',
  },
  {
    id: 100,
    name: 'Constitution of the Asia-Pacific Telecommunity. Bangkok, 27 March 1976',
    mtdsg_no: 'XXV-2',
    signed: 1976, ratified: 1977,
    era: 'Deng (1978–92)',
    cat: 'Technology & science',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: 1,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXV-2&chapter=25&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXV-2.',
  },
  {
    id: 101,
    name: 'Agreement establishing the Asia-Pacific Institute for Broadcasting Development. Kuala Lumpur, 12 August 1977',
    mtdsg_no: 'XXV-3',
    signed: null, ratified: 1988,
    era: 'Deng (1978–92)',
    cat: 'Technology & science',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'none',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXV-3&chapter=25&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXV-3.',
  },
  {
    id: 102,
    name: 'Convention on the prohibition of military or any other hostile use of environmental modification techniques',
    mtdsg_no: 'XXVI-1',
    signed: null, ratified: 2005,
    era: 'Hu (2002–12)',
    cat: 'Arms control / CBRN',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1976,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVI-1&chapter=26&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVI-1.',
  },
  {
    id: 103,
    name: 'Convention on Prohibitions or Restrictions on the Use of Certain Conventional Weapons which may be deemed to be Excessively Injurious or to have Indiscriminate Effects (with Protocols I, II and III)',
    mtdsg_no: 'XXVI-2',
    signed: 1981, ratified: 1982,
    era: 'Deng (1978–92)',
    cat: 'Arms control / CBRN',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1980,
    entry_into_force: null,
    signing_lag_years: 1,
    ratification_lag_years: 1,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'binary',
    enforcement_channel: 'centralised',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVI-2&chapter=26&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVI-2.',
  },
  {
    id: 104,
    name: 'Vienna Convention for the Protection of the Ozone Layer',
    mtdsg_no: 'XXVII-2',
    signed: null, ratified: 1989,
    era: 'Deng (1978–92)',
    cat: 'Environmental',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1985,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVII-2&chapter=27&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVII-2.',
  },
  {
    id: 105,
    name: 'Amendment to the Montreal Protocol on Substances that Deplete the Ozone Layer. Kigali, 15 October 2016',
    mtdsg_no: 'XXVII-2-f',
    signed: null, ratified: 2021,
    era: 'Xi (2012–)',
    cat: 'Environmental',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: null,
    adoption_percentile: null,
    reservations: ['Declaration : I.  Article 5 of the Montreal Protocol on Substances that Deplete the Ozone Layer shall not apply to the Hong Kong Special Administrative Region and the Macao Special Administrative Region of the People’s Republic of China. II.  In accordance with the Basic Law of the Hong Kong Special Administrative Region of the People’s Republic of China and the Basic Law of the Macao Special Administrative Region of the People’s Republic of China, the Government of the People’s Republic of China decides that the above-mentioned Amendment shall apply to the Macao Special Administrative Region of the People’s Republic of China, and unless otherwise notified by the Government of the People’s Republic of China, shall not apply to the Hong Kong Special Administrative Region of the People’s Republic of China.'],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVII-2-f&chapter=27&clang=_en',
    tags: [],
    notes: 'Declaration : I. Article 5 of the Montreal Protocol on Substances that Deplete the Ozone Layer shall not apply to the Hong Kong Special Administrative Region and the Macao Special Administrative Re...',
  },
  {
    id: 106,
    name: 'Cartagena Protocol on Biosafety to the Convention on Biological Diversity',
    mtdsg_no: 'XXVII-8-a',
    signed: 2000, ratified: 2005,
    era: 'Hu (2002–12)',
    cat: 'Environmental',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 2000,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 5,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVII-8-a&chapter=27&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVII-8-a.',
  },
  {
    id: 107,
    name: 'United Nations Convention to Combat Desertification in those Countries Experiencing Serious Drought and/or Desertification, Particularly in Africa',
    mtdsg_no: 'XXVII-10',
    signed: 1994, ratified: 1997,
    era: 'Jiang (1992–02)',
    cat: 'Environmental',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: 1994,
    entry_into_force: null,
    signing_lag_years: 0,
    ratification_lag_years: 3,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVII-10&chapter=27&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVII-10.',
  },
  {
    id: 108,
    name: 'Rotterdam Convention on the Prior Informed Consent Procedure for Certain Hazardous Chemicals and Pesticides in International Trade. Rotterdam, 10 September 1998',
    mtdsg_no: 'XXVII-14',
    signed: 1999, ratified: 2005,
    era: 'Hu (2002–12)',
    cat: 'Environmental',
    multi: true,
    parties: 'Multilateral',
    by: true, rat: true, imp: false,
    status: 'in force',
    treaty_opened: null,
    entry_into_force: null,
    signing_lag_years: null,
    ratification_lag_years: 6,
    adoption_percentile: null,
    reservations: [],
    optional_protocols_accepted: false,
    complaints_mechanism_accepted: false,
    reporting_status: 'n/a',
    compliance_flags: [],
    behaviour_status: null,
    obligation_type: 'scalar',
    enforcement_channel: 'distributed',
    verification_mechanism: false,
    source_url: 'https://treaties.un.org/Pages/ViewDetails.aspx?src=TREATY&mtdsg_no=XXVII-14&chapter=27&clang=_en',
    tags: [],
    notes: 'UN Treaty Collection XXVII-14.',
  },
